# Generated by Django 3.2.9 on 2021-11-09 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='csvModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csvFileName', models.CharField(max_length=50)),
                ('csvFile', models.FileField(upload_to='tpData/csv/')),
            ],
        ),
        migrations.CreateModel(
            name='ttlModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttlFileName', models.CharField(max_length=50)),
                ('ttlFile', models.FileField(upload_to='tpData/ttl/')),
            ],
        ),
    ]
